version: '3.8'

services:
  # Nginx for serving frontend and acting as a reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # React frontend service
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network

  # Spring Boot backend service
  backend:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    depends_on:
      - db
    networks:
      - app-network

  # MariaDB service for the database
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

# Named volume for MariaDB persistence
volumes:
  db_data:

# Define the custom network for the services
networks:
  app-network:
    driver: bridge
